version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: modisarkar-nextjs-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Anonymous volume to prevent overriding container's node_modules with host's
      - /app/.next        # Anonymous volume for nextjs build cache
    env_file:
      - .env.local
    command: npm run dev
    restart: unless-stopped
